# Google Cloud Build configuration para despliegue en Cloud Run
steps:
  # Validaci칩n r치pida del lockfile usando pnpm (igual que en el Dockerfile)
  - name: 'node:18'
    entrypoint: sh
    args:
      - -c
      - |
        set -e
        corepack enable
        pnpm install --frozen-lockfile

  # Construcci칩n de la imagen y publicaci칩n en Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_SERVICE_NAME}:${_IMAGE_TAG}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_SERVICE_NAME}:${_IMAGE_TAG}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_SERVICE_NAME}:latest'

  # 游댢 Limpieza de command/args obsoletos en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: clear-run-command
    entrypoint: bash
    args:
      - -c
      - |
        echo "Limpiando command/args de Cloud Run antes del despliegue..."
        gcloud run services update '${_SERVICE_NAME}' \
          --region '${_REGION}' \
          --clear-command \
          --clear-args \
          --project '$PROJECT_ID' || true

  # Despliegue en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy '${_SERVICE_NAME}' \
          --image '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_SERVICE_NAME}:${_IMAGE_TAG}' \
          --region '${_REGION}' \
          --allow-unauthenticated \
          --platform managed \
          --add-cloudsql-instances '${_CLOUDSQL_CONNECTION}' \
          --set-env-vars "NODE_ENV=production,PORT=8080,JWT_SECRET=${_JWT_SECRET},DATABASE_URL=${_DATABASE_URL},INSTANCE_CONNECTION_NAME=${_CLOUDSQL_CONNECTION}" \
          --project '$PROJECT_ID'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_SERVICE_NAME}:${_IMAGE_TAG}'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_SERVICE_NAME}:latest'

substitutions:
  _SERVICE_NAME: library-management-system
  _REGION: us-central1
  _ARTIFACT_REPOSITORY: library-management-system
  _IMAGE_TAG: latest
  _JWT_SECRET: ''
  _DATABASE_URL: 'postgresql://library_user:_a1Dk4WYkKl_YRBlPrwemtTfL8yGaZXfWNIxb50-nag@/library_db?host=/cloudsql/where-is-the-library:us-central1:biblioteca-sql'
  _CLOUDSQL_CONNECTION: 'where-is-the-library:us-central1:biblioteca-sql'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
