version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library_app_dev
    command: pnpm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=dev-secret
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - library_dev_network

networks:
  library_dev_network:
    driver: bridge
