version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library_app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - JWT_SECRET=your-production-jwt-secret
      - ALLOWED_ORIGINS=http://localhost:3000
    networks:
      - library_network
    restart: unless-stopped

networks:
  library_network:
    driver: bridge
